# There are more fmt options available when using rustfmt nightly
#
# $ rustup toolchain install nightly
# $ rustup component add rustfmt --toolchain nightly
# $ cargo +nightly fmt
#
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

# Line lengths
normalize_comments = true
comment_width = 110
max_width = 110

# When to reorder fields
merge_imports = true
reorder_impl_items = true

# When to remove newlines
fn_single_line = false
inline_attribute_width = 60
overflow_delimited_expr = true

# When to keep newlines
blank_lines_upper_bound = 2
newline_style = "Unix"

# Terse syntax
use_try_shorthand = true
